# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper-cardinalR.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
options(repos = "https://cloud.r-project.org") ## set up CRAN mirror
knitr::opts_chunk$set(
  echo = FALSE,
  cache=FALSE, 
  message=FALSE, 
  warning=FALSE,
  out.width = "100%",
  fig.pos = "!")



## ----set-seed-----------------------------------------------------------------
set.seed(20240412)


## ----install-libraries, include=FALSE, warning=FALSE, echo=FALSE--------------

options(repos = c(CRAN = "https://cran.rstudio.com")) # Setup mirror

packages_to_check <- c("remotes", "cardinalR", "tidyverse", "kableExtra", "geozoo", "patchwork", "colorspace")

for (pkg in packages_to_check) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    message(paste("Installing package:", pkg))
    install.packages(pkg)
  } else {
    installed_version <- packageVersion(pkg)
    available_version <- tryCatch({
      utils::packageDescription(pkg)$Version
    }, error = function(e) NA) # Handle cases where package info isn't readily available

    if (!is.na(available_version) && installed_version < package_version(available_version)) {
      message(paste("A newer version of package", pkg, "is available. Updating..."))
      install.packages(pkg)
    } else {
      message(paste("Package", pkg, "is up-to-date (version", installed_version, ")."))
    }
  }
}



## ----load-libraries-----------------------------------------------------------
library(cardinalR)
library(tidyverse)
library(kableExtra)
library(geozoo)
library(patchwork)
library(colorspace)
library(crosstalk)


## -----------------------------------------------------------------------------
#| label: plot-theme
theme_set(theme_linedraw() +
   theme(
     aspect.ratio = 1,
     plot.background = element_rect(fill = 'transparent', colour = NA),
     plot.title = element_text(size = 7, hjust = 0.5, vjust = -0.5),
     panel.background = element_rect(fill = 'transparent', 
                                     colour = NA),
     panel.grid.major = element_blank(), 
     panel.grid.minor = element_blank(), 
     axis.title.x = element_blank(), axis.title.y = element_blank(),
     axis.text.x = element_blank(), axis.ticks.x = element_blank(),
     axis.text.y = element_blank(), axis.ticks.y = element_blank(),
     legend.background = element_rect(fill = 'transparent', 
                                      colour = NA),
     legend.key = element_rect(fill = 'transparent', 
                               colour = NA),
     legend.position = "bottom", 
     legend.title = element_blank(), 
     legend.text = element_text(size=4),
     legend.key.height = unit(0.25, 'cm'),
     legend.key.width = unit(0.25, 'cm'),
     plot.margin = margin(0, 0, 0, 0)
   )
)


## -----------------------------------------------------------------------------
#| label: import-scripts
source("scripts/additional_functions.R")


## -----------------------------------------------------------------------------
main_tb <- tibble(arg = c("n",
                          "k",
                          "loc",
                          "scale",
                          "shape",
                          "rotation",
                          "is_bkg"),
                  type = c("numeric (vector)",
                           "numeric",
                           "numeric (matrix)",
                           "numeric (vector)",
                           "character (vector)",
                           "numeric (list)",
                           "boolean"),
                        exp = c("Number of points in each cluster.",
                                "Number of clusters.",
                                "Locations/centroids of clusters.",
                                "Scaling factors of clusters.",
                                "Shapes of clusters.",
                                "Rotation matrices, one per cluster.",
                                "Background noise should exist or not."))


## ----main-tb-html, eval=knitr::is_html_output()-------------------------------
# main_tb |>
#   kable(caption = "The main arguments for `gen_multicluster()`.", col.names = c("Argument", "Type", "Explanation"))


## ----main-tb-pdf, eval=knitr::is_latex_output()-------------------------------
main_tb |> 
  kable(caption = "The main arguments for gen\\_multicluster().", format="latex", col.names = c("Argument", "Type", "Explanation"), booktabs = T, table.pos = "H")  |>
  column_spec(1, width = "2cm") |>
  column_spec(2, width = "3cm") |>
  column_spec(3, width = "8cm")


## -----------------------------------------------------------------------------
noise_fun_tb <- tibble(fun = c("gen_noisedims",
                            "gen_wavydims1",
                            "gen_wavydims2",
                            "gen_wavydims3"), 
                        exp = c("Gaussian noise dimensions with optional mean and standard deviation.",
                                "Wavy noise dimensions based on a user-specified theta sequence with added jitter.",
                                "Wavy noise dimensions using polynomial transformations of an existing dimension vector.",
                                "Wavy noise dimensions using a combination of polynomial and sine transformations based on the first three dimensions of a dataset."))


## ----noise-tb-html, eval=knitr::is_html_output()------------------------------
# noise_fun_tb |>
#   kable(caption = "cardinalR noise dimensions generation functions", col.names = c("Function", "Explanation"))


## ----noise-tb-pdf, eval=knitr::is_latex_output()------------------------------
noise_fun_tb |> 
  kable(caption = "cardinalR noise dimensions generation functions", format="latex", col.names = c("Function", "Explanation"), booktabs = T)  |>
  column_spec(1, width = "4cm") |>
  column_spec(2, width = "8cm")


## -----------------------------------------------------------------------------
odd_shapes_tb <- tibble(fun = c("make_mobiusgau",
                                "make_multigau",
                                "make_curvygau",
                                "make_klink_circles",
                                "make_chain_circles",
                                "make_klink_curvycycle",
                                "make_chain_curvycycle",
                                "make_gaucircles",
                                "make_gaucurvycycle",
                                "make_onegrid",
                                "make_twogrid_overlap",
                                "make_twogrid_shift",
                                "make_shape_para",
                                "make_three_clust_"), 
                        exp = c(
    "Möbius-like cluster combined with a Gaussian.",
    "Multiple Gaussian clusters in high-dimensional space.",
    "Curvilinear cluster with a Gaussian cluster.",
    "K-link circular clusters (non-linear circular patterns).",
    "Chain-like circular clusters connected sequentially.",
    "K-link curvy cycle clusters (curvilinear loop structures).",
    "Chain-like curvy cycle clusters connected sequentially.",
    "Circular clusters with a Gaussian cluster in the middle.",
    "Curvy circular clusters with a Gaussian cluster in the middle.",
    "Single grid in two dimensions.",
    "Two overlapping grids.",
    "Two grids shifted relative to each other.",
    "Parallel shaped clusters.",
    "Three clusters with different shapes. (eg:- 01, 02, ..., 20)"))


## ----odd-shape-tb-html, eval=knitr::is_html_output()--------------------------
# odd_shapes_tb |>
#   kable(caption = "cardinalR multiple clusters generation functions", col.names = c("Function", "Explanation"))


## ----odd-shape-tb-pdf, eval=knitr::is_latex_output()--------------------------
odd_shapes_tb |> 
  kable(caption = "cardinalR multiple clusters generation functions", format="latex", col.names = c("Function", "Explanation"), booktabs = T)  |>
  column_spec(1, width = "3.5cm") |>
  column_spec(2, width = "8.5cm")


## -----------------------------------------------------------------------------
add_fun_tb <- tibble(fun = c("gen_bkgnoise",
                            "randomize_rows",
                            "relocate_clusters",
                            "gen_nproduct",
                            "gen_nsum",
                            "gen_rotation",
                            "normalize_data"), 
                        exp = c("Adds background noise.",
                                "Randomizes the rows.",
                                "Relocates the clusters.",
                                "Generates a vector of positive integers whose product is approximately equal to a target value.",
                                "Generates a vector of positive integers whose summation is approximately equal to a target value.", 
                                "Generates rotations.", 
                                "Normalizes data."))


## ----add-tb-html, eval=knitr::is_html_output()--------------------------------
# add_fun_tb |>
#   kable(caption = "cardinalR additional functions", col.names = c("Function", "Explanation"))


## ----add-tb-pdf, eval=knitr::is_latex_output()--------------------------------
add_fun_tb |> 
  kable(caption = "cardinalR additional functions", format="latex", col.names = c("Function", "Explanation"), booktabs = T)  |>
  column_spec(1, width = "4cm") |>
  column_spec(2, width = "8cm")


## ----gen-five-clust-data, echo=TRUE-------------------------------------------

positions <- geozoo::simplex(p=4)$points
positions <- positions * 0.8

## To generate data
five_clusts <- gen_multicluster(n = c(2250, 1500, 750, 1250, 1750), k = 5,
                       loc = positions,
                       scale = c(0.4, 0.35, 0.3, 1, 0.3),
                       shape = c("helicalspiral", "hemisphere", "unifcube", 
                                 "cone", "gaussian"),
                       rotation = NULL,
                       is_bkg = FALSE)


## ----highd-data, eval=knitr::is_html_output(), fig.cap="`langevitour` output showing five synthetic clusters with distinct geometric structures: a helical spiral, a hemisphere, a uniform cube, a cone, and a Gaussian cluster."----
# 
# langevitour::langevitour(five_clusts[, -5], group = five_clusts$cluster, levelColors = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e'))


## ----five-clusts-projections1-------------------------------------------------
scaled_data <- scale_data_manual(five_clusts[, -5])

## First projection
projection <- cbind(
  c(-0.59692,0.46414,0.42436,-0.10048),
  c(-0.54999,-0.67673,-0.03631,-0.01193))

proj_obj1 <- get_projection(projection = projection, 
                            proj_scale = 1.23, 
                            scaled_data = scaled_data, 
                            axis_param = list(limits = 1,
                                              axis_scaled = 0.8, 
                                              axis_pos_x = -0.9, 
                                              axis_pos_y = -0.9, 
                                              threshold = 0.05))

proj_obj1[["cluster"]] <- as.character(five_clusts$cluster)

five_clusts_proj1 <- plot_proj(
  proj_obj = proj_obj1, 
  point_param = c(1.5, 0.2), # size, alpha, color
  plot_limits = c(-1.1, 1), 
  title = "a1", 
  cex = 2, 
  axis_text_size = 4,
  is_color = TRUE) + scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(legend.text = element_text(size = 10))



## ----five-clusts-projections2-------------------------------------------------
## Second projection
projection <- cbind(
  c(0.34673,-0.35774,0.66272,0.27298),
  c(0.24023,0.01170,-0.41886,0.72707))

proj_obj2 <- get_projection(projection = projection, 
                            proj_scale = 1.23, 
                            scaled_data = scaled_data, 
                            axis_param = list(limits = 1,
                                              axis_scaled = 0.8, 
                                              axis_pos_x = -0.9, 
                                              axis_pos_y = -0.9, 
                                              threshold = 0.07))

proj_obj2[["cluster"]] <- as.character(five_clusts$cluster)

five_clusts_proj2 <- plot_proj(
  proj_obj = proj_obj2, 
  point_param = c(1.5, 0.2), # size, alpha, color
  plot_limits = c(-1.1, 1.2), 
  title = "a2", 
  cex = 2, 
  axis_text_size = 4,
  is_color = TRUE) + scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(legend.text = element_text(size = 10))


## ----five-clusts-projections3-------------------------------------------------
## Third projection
projection <- cbind(
  c(0.47388,-0.20984,-0.56560,0.41644),
  c(-0.51124,-0.60184,0.06463,0.36627))

proj_obj3 <- get_projection(projection = projection, 
                            proj_scale = 1.23, 
                            scaled_data = scaled_data, 
                            axis_param = list(limits = 1,
                                              axis_scaled = 0.8, 
                                              axis_pos_x = -0.9, 
                                              axis_pos_y = -0.9, 
                                              threshold = 0.05))

proj_obj3[["cluster"]] <- as.character(five_clusts$cluster)

five_clusts_proj3 <- plot_proj(
  proj_obj = proj_obj3, 
  point_param = c(1.5, 0.2), # size, alpha, color
  plot_limits = c(-1.1, 1.1), 
  title = "a3", 
  cex = 2, 
  axis_text_size = 4,
  is_color = TRUE) + scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(legend.text = element_text(size = 10))



## ----highd-proj, eval=knitr::is_latex_output(), fig.pos='H', fig.cap="Three $2\\text{-}D$ projections from $4\\text{-}D$, for the five clusters data. The helical spiral cluster is represented in dark green, the hemisphere cluster in orange, the uniform cube-shaped cluster in purple, the blunted cone cluster in pink, and the Gaussian-shaped cluster in light green."----
#| fig-width: 12
#| fig-height: 4

five_clusts_proj1 + five_clusts_proj2 + five_clusts_proj3 +
  plot_layout(ncol = 3, guides = "collect") 


## ----layouts------------------------------------------------------------------

tsne_data <- read_rds("data/five_clusts/five_clusts_tsne_perplexity_30.rds") 

nldr1 <- tsne_data |>
  ggplot(aes(x = tSNE1,
             y = tSNE2,
             color = cluster))+
  geom_point(alpha=0.1, size=1) +
  interior_annotation("a", c(0.08, 0.93)) + 
  scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 10)) 

umap_data <- read_rds("data/five_clusts/five_clusts_umap_n-neigbors_15_min-dist_0.1.rds") 

nldr2 <- umap_data |>
  ggplot(aes(x = UMAP1,
             y = UMAP2,
             color = cluster))+
  geom_point(alpha=0.1, size=1) +
  interior_annotation("b", c(0.08, 0.93)) + 
  scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 10)) 

phate_data <- read_rds("data/five_clusts/five_clusts_phate_knn_5.rds") 

nldr3 <- phate_data |>
  ggplot(aes(x = PHATE1,
             y = PHATE2,
             color = cluster))+
  geom_point(alpha=0.1, size=1) +
  interior_annotation("c", c(0.08, 0.93)) + 
  scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 10)) 

trimap_data <- read_rds("data/five_clusts/five_clusts_trimap_n-inliers_12_n-outliers_4_n-random_3.rds") 

nldr4 <- trimap_data |>
  ggplot(aes(x = TriMAP1,
             y = TriMAP2,
             color = cluster))+
  geom_point(alpha=0.1, size=1) +
  interior_annotation("d", c(0.08, 0.93)) + 
  scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 10))  

pacmap_data <- read_rds("data/five_clusts/five_clusts_pacmap_n-neighbors_10_init_random_MN-ratio_0.5_FP-ratio_2.rds") 

nldr5 <- pacmap_data |>
  ggplot(aes(x = PaCMAP1,
             y = PaCMAP2,
             color = cluster))+
  geom_point(alpha=0.1, size=1) +
  interior_annotation("e", c(0.08, 0.93)) + 
  scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 10)) 

pca_data <- read_rds("data/five_clusts/five_clusts_pca.rds") 

nldr6 <- pca_data |>
  ggplot(aes(x = pca1,
             y = pca2,
             color = cluster))+
  geom_point(alpha=0.1, size=1) +
  interior_annotation("f", c(0.08, 0.93)) + 
  scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e')) +
  theme(aspect.ratio = 1,
        legend.text = element_text(size = 10)) 


## ----label = "fig-nldr-layouts", fig.pos="H", fig.cap="Six different dimension reduction representations of the five clusters data using default hyperparameter settings: (a) tSNE, (b) UMAP, (c) PAHTE, (d) TriMAP, (e) PaCMAP, and (f) PCA."----

nldr1 + nldr2 + nldr3 +
  nldr4 + nldr5 + nldr6 +
  plot_layout(ncol = 3, guides = "collect")

